"use client";

import { useEffect, useMemo, useState } from "react";
import type { StrategyCouncilMemoPayload } from "@/lib/services/ai";
import { STRATEGY_COUNCIL_PRINT_STORAGE_KEY } from "@/lib/intelligence/strategy-council-print-key";

const printCss = `
@media print {
  @page { margin: 18mm; }
  body { background: white !important; color: #111 !important; }
  .no-print { display: none !important; }
}
`;

export default function StrategyCouncilPrintPage() {
  const [payload, setPayload] = useState<StrategyCouncilMemoPayload | null>(null);

  useEffect(() => {
    try {
      const raw = sessionStorage.getItem(STRATEGY_COUNCIL_PRINT_STORAGE_KEY);
      if (raw) setPayload(JSON.parse(raw) as StrategyCouncilMemoPayload);
    } catch {
      setPayload(null);
    }
  }, []);

  const title = useMemo(() => payload?.pdfLayout.documentTitle ?? "Strategy Council Memo", [payload]);

  if (!payload) {
    return (
      <div className="min-h-screen bg-[#0b0f14] px-6 py-16 text-center text-gray-400">
        <p className="font-serif text-lg text-white">No memo payload in session.</p>
        <p className="mt-2 text-sm">Generate a memo from the Strategy Council page, then open this print view again.</p>
      </div>
    );
  }

  return (
    <div className="relative min-h-screen bg-[#f4f1ea] text-[#1a1a1a] print:bg-white">
      <style dangerouslySetInnerHTML={{ __html: printCss }} />
      <div
        className="pointer-events-none fixed inset-0 z-0 hidden items-center justify-center font-serif text-[56px] leading-none text-black/[0.06] print:flex"
        aria-hidden
      >
        Institutional Memory
      </div>

      <div className="no-print border-b border-black/10 bg-[#0b0f14] px-4 py-3 text-center text-xs text-gray-400">
        <button
          type="button"
          className="rounded border border-white/20 px-4 py-1.5 text-white hover:bg-white/10"
          onClick={() => window.print()}
        >
          Print / Save PDF
        </button>
      </div>

      <article className="relative z-10 mx-auto max-w-3xl px-8 py-12 font-serif">
        <header className="border-b border-black/15 pb-6">
          <p className="text-[10px] uppercase tracking-[0.35em] text-black/45">Pemabu — Strategy Council</p>
          <h1 className="mt-2 text-3xl font-normal tracking-tight text-black">{title}</h1>
          <p className="mt-2 text-sm text-black/55">{new Date().toISOString().slice(0, 10)}</p>
        </header>

        <div className="mt-8 max-w-none">
          {payload.pdfLayout.sections.map((s) => (
            <section key={s.id} className="mb-10 break-inside-avoid">
              <h2 className="mb-3 text-xl font-semibold text-black">{s.heading}</h2>
              <div className="whitespace-pre-wrap text-[15px] leading-[1.65] text-black/85">{s.bodyMarkdown}</div>
            </section>
          ))}
        </div>

        <footer className="mt-12 border-t border-black/10 pt-6 text-[11px] leading-relaxed text-black/55">
          <p>
            This report is generated by local automated logic. It does not constitute financial advice, investment
            recommendations, or regulated advisory services.
          </p>
          <p className="mt-2">
            Pemabu is sovereign software for allocation protocol monitoring; consult qualified professionals where
            required by law.
          </p>
        </footer>
      </article>
    </div>
  );
}
