/**
 * Validated Anthropic model ID constants.
 *
 * PRIMARY  — Claude Sonnet 4 (balanced: quality + cost for structured outputs
 *            and multi-section documents; default for Strategy Council memo).
 * FAST     — Claude Haiku 4.5 (low-latency, low-cost; for short narrative
 *            generation, single-holding explanations, and governance summaries
 *            where brevity is more important than depth).
 *
 * NEVER use raw model ID strings outside this file.  If Anthropic renames a
 * model, update here and the entire codebase follows.
 *
 * STRATEGY_COUNCIL_MODEL is not defined here because it may be overridden at
 * runtime via STRATEGY_COUNCIL_ANTHROPIC_MODEL env var (see lib/services/ai.ts).
 */
export const AI_MODELS = {
  /** Claude Sonnet 4 — primary quality tier */
  PRIMARY: "claude-sonnet-4-20250514",
  /** Claude Haiku 4.5 — fast / cost-optimised tier */
  FAST: "claude-haiku-4-5-20251001",
} as const;

export type AiModelId = (typeof AI_MODELS)[keyof typeof AI_MODELS];

/**
 * Mandatory non-advisory disclaimer appended to all AI-generated outputs
 * that are displayed to end users.  Always append; never omit.
 */
export const AI_DISCLAIMER =
  "This output is generated by an AI model and is for informational purposes only. " +
  "It does not constitute financial, investment, legal, or tax advice. " +
  "Always consult a qualified professional before making financial decisions.";

/**
 * Startup validation — call once from the app entry point (e.g. next.config.ts
 * instrumentation hook or the first server action that uses AI) to surface
 * misconfiguration early rather than at the first real API call.
 *
 * Throws if ANTHROPIC_API_KEY is absent.
 * Warns if STRATEGY_COUNCIL_ANTHROPIC_MODEL is set to an unrecognised value.
 */
export function validateAnthropicConfig(): void {
  if (!process.env.ANTHROPIC_API_KEY?.trim()) {
    throw new Error(
      "[ai-models] ANTHROPIC_API_KEY is not set. All AI features will fail at runtime. " +
      "Set it in .env.local (development) or the deployment environment (production).",
    );
  }

  const councilModel = process.env.STRATEGY_COUNCIL_ANTHROPIC_MODEL?.trim();
  if (councilModel && !councilModel.startsWith("claude-")) {
    console.warn(
      `[ai-models] STRATEGY_COUNCIL_ANTHROPIC_MODEL="${councilModel}" does not look like a ` +
      `valid Anthropic model ID (expected to start with "claude-"). Check for typos.`,
    );
  }
}
