import React from "react";
import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import type { StrategyCouncilMemoPayload } from "@/lib/services/ai";

const styles = StyleSheet.create({
  page: {
    paddingTop: 44,
    paddingBottom: 56,
    paddingHorizontal: 48,
    fontFamily: "Times-Roman",
    fontSize: 10.5,
    color: "#141414",
    lineHeight: 1.45,
  },
  watermark: {
    position: "absolute",
    top: "38%",
    left: 0,
    right: 0,
    textAlign: "center",
    fontSize: 42,
    color: "#c9c4bc",
    opacity: 0.35,
    fontFamily: "Times-Roman",
  },
  kicker: { fontSize: 8, letterSpacing: 2.2, color: "#5c5c5c", textTransform: "uppercase" },
  title: { marginTop: 10, fontSize: 20, fontFamily: "Times-Bold" },
  date: { marginTop: 6, fontSize: 9, color: "#5c5c5c" },
  rule: { marginTop: 14, marginBottom: 18, borderBottomWidth: 0.5, borderBottomColor: "#bfbfbf" },
  sectionTitle: { fontSize: 13, fontFamily: "Times-Bold", marginBottom: 8, color: "#0a0a0a" },
  body: { fontSize: 10.5, textAlign: "justify", color: "#222" },
  footer: {
    position: "absolute",
    bottom: 32,
    left: 48,
    right: 48,
    borderTopWidth: 0.5,
    borderTopColor: "#bfbfbf",
    paddingTop: 10,
    fontSize: 8,
    color: "#555",
    lineHeight: 1.35,
  },
});

function stripMarkdownLite(s: string): string {
  return s.replace(/\*\*([^*]+)\*\*/g, "$1").replace(/\*([^*]+)\*/g, "$1").replace(/^#+\s?/gm, "");
}

export function StrategyCouncilMemoPdfDocument({ payload }: { payload: StrategyCouncilMemoPayload }) {
  const title = payload.pdfLayout.documentTitle ?? "Strategy Council — Monthly Memo";
  const date = new Date().toISOString().slice(0, 10);

  return (
    <Document title={title} author="Pemabu" subject="Strategy Council Memo">
      <Page size="A4" style={styles.page}>
        <Text style={styles.watermark} fixed>
          Institutional Memory
        </Text>
        <Text style={styles.kicker}>Pemabu — Strategy Council</Text>
        <Text style={styles.title}>{title}</Text>
        <Text style={styles.date}>{date}</Text>
        <View style={styles.rule} />
        {payload.pdfLayout.sections.map((s) => (
          <View key={s.id} wrap={false}>
            <Text style={styles.sectionTitle}>{s.heading}</Text>
            <Text style={styles.body}>{stripMarkdownLite(s.bodyMarkdown)}</Text>
          </View>
        ))}
        <Text style={styles.footer} fixed>
          Non-fiduciary notice: This PDF is generated by local automated logic from your portfolio aggregates. It does
          not constitute financial advice, investment recommendations, or regulated advisory services. Pemabu is
          sovereign execution and allocation protocol software; consult qualified professionals where required by law.
          Pemabu is not a registered investment advisor. All outputs are for informational purposes only and do not
          constitute financial advice.
        </Text>
      </Page>
    </Document>
  );
}
