-- ─────────────────────────────────────────────────────────────────────────────
-- REMEDIATION MIGRATION
-- Target: databases that already ran 20260601000001 in its original form
-- Safe to run on new installs: all operations are conditional / idempotent
-- ─────────────────────────────────────────────────────────────────────────────


-- ── FIX A: Rename price_locked_usd → price_paid_usd ─────────────────────────
-- Only runs if the old column name still exists.
-- New installs already have price_paid_usd from the corrected 20260601000001.

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name   = 'user_subscriptions'
      and column_name  = 'price_locked_usd'
  ) then
    alter table public.user_subscriptions
      rename column price_locked_usd to price_paid_usd;

    raise notice 'Renamed price_locked_usd to price_paid_usd.';
  else
    raise notice 'price_paid_usd already exists — column rename skipped.';
  end if;
end
$$;


-- ── FIX B: Widen status check constraint to include trial ────────────────────
-- Drops the old constraint (if present by its original name) and recreates it.
-- If the constraint was already updated by a prior apply of the fixed
-- 20260601000001, the drop will be a no-op and the add will still succeed
-- because PostgreSQL allows recreating a constraint with the same definition.

do $$
begin
  -- Drop old constraint by name if it exists
  -- The constraint name is generated by Postgres as user_subscriptions_status_check
  -- on a plain CHECK without an explicit name. Adjust if your DB used a custom name.
  if exists (
    select 1
    from information_schema.table_constraints
    where table_schema     = 'public'
      and table_name       = 'user_subscriptions'
      and constraint_type  = 'CHECK'
      and constraint_name  = 'user_subscriptions_status_check'
  ) then
    alter table public.user_subscriptions
      drop constraint user_subscriptions_status_check;

    raise notice 'Dropped old status check constraint.';
  else
    raise notice 'Old status check constraint not found — drop skipped.';
  end if;
end
$$;

-- Recreate with full canonical set including trial
-- This is safe to run even if constraint was already correct
alter table public.user_subscriptions
  drop constraint if exists user_subscriptions_status_check;

alter table public.user_subscriptions
  add constraint user_subscriptions_status_check
  check (status in (
    'active',
    'cancelled',
    'expired',
    'complimentary',
    'trial'
  ));


-- ── VERIFY: Confirm final column and constraint state ────────────────────────

do $$
declare
  col_exists boolean;
begin
  -- Verify price_paid_usd exists
  select exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name   = 'user_subscriptions'
      and column_name  = 'price_paid_usd'
  ) into col_exists;

  if not col_exists then
    raise exception 'REMEDIATION FAILED: price_paid_usd column not found on user_subscriptions.';
  end if;

  -- Verify price_locked_usd is gone
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name   = 'user_subscriptions'
      and column_name  = 'price_locked_usd'
  ) then
    raise exception 'REMEDIATION FAILED: price_locked_usd still exists on user_subscriptions.';
  end if;

  raise notice 'VERIFIED: price_paid_usd column present, price_locked_usd absent.';
  raise notice 'VERIFIED: status check constraint updated. Schema remediation complete.';
end
$$;
